package org.mlm.browkorftv.settings

object BrowkorfSettingsKeys {
    const val CATEGORY_GENERAL = "browkorf.settings.category.general"
    const val CATEGORY_HOME_PAGE = "browkorf.settings.category.home_page"
    const val CATEGORY_SEARCH = "browkorf.settings.category.search"
    const val CATEGORY_USER_AGENT = "browkorf.settings.category.user_agent"
    const val CATEGORY_WEB_ENGINE = "browkorf.settings.category.web_engine"
    const val CATEGORY_AD_BLOCK = "browkorf.settings.category.ad_block"
    const val CATEGORY_UPDATES = "browkorf.settings.category.updates"
    const val CATEGORY_PROXY = "browkorf.settings.category.proxy"

    const val THEME = "browkorf.settings.theme"
    const val LANGUAGE = "browkorf.settings.language"
    const val FORCE_DARK_WEBPAGE = "browkorf.settings.force_dark_webpage"
    const val KEEP_SCREEN_ON = "browkorf.settings.keep_screen_on"
    const val INCOGNITO_MODE = "browkorf.settings.incognito_mode"
    const val ALLOW_AUTOPLAY_MEDIA = "browkorf.settings.allow_autoplay_media"
    const val HOME_PAGE_MODE = "browkorf.settings.home_page_mode"
    const val CUSTOM_HOME_PAGE_URL = "browkorf.settings.custom_home_page_url"
    const val SEARCH_ENGINE = "browkorf.settings.search_engine"
    const val CUSTOM_SEARCH_ENGINE_URL = "browkorf.settings.custom_search_engine_url"
    const val USER_AGENT = "browkorf.settings.user_agent"
    const val WEB_ENGINE = "browkorf.settings.web_engine"
    const val AD_BLOCK_ENABLED = "browkorf.settings.ad_block_enabled"
    const val AD_BLOCK_LIST_URL = "browkorf.settings.ad_block_list_url"
    const val AUTO_CHECK_UPDATES = "browkorf.settings.auto_check_updates"
    const val UPDATE_CHANNEL = "browkorf.settings.update_channel"
    const val CHECK_FOR_UPDATES = "browkorf.settings.check_for_updates"
    const val USE_HTTP_PROXY = "browkorf.settings.use_http_proxy"
    const val PROXY_URL = "browkorf.settings.proxy_url"
    const val DIRECTIONAL_NAVIGATION_MODE = "browkorf.settings.directional_navigation_mode"
    const val NEW_TAB_BUTTON_AT_START = "browkorf.settings.new_tab_button_at_start"
    const val CONTEXT_MENU_ON_LONG_PRESS = "browkorf.settings.context_menu_on_long_press"
    const val SINGLE_TAB_MODE = "browkorf.settings.single_tab_mode"

    const val FORCE_DARK_WEBPAGE_DESCRIPTION = "browkorf.settings.force_dark_webpage.description"
    const val KEEP_SCREEN_ON_DESCRIPTION = "browkorf.settings.keep_screen_on.description"
    const val INCOGNITO_MODE_DESCRIPTION = "browkorf.settings.incognito_mode.description"
    const val WEB_ENGINE_DESCRIPTION = "browkorf.settings.web_engine.description"
    const val CHECK_FOR_UPDATES_DESCRIPTION = "browkorf.settings.check_for_updates.description"
    const val USE_HTTP_PROXY_DESCRIPTION = "browkorf.settings.use_http_proxy.description"
    const val PROXY_URL_DESCRIPTION = "browkorf.settings.proxy_url.description"
    const val DIRECTIONAL_NAVIGATION_MODE_DESCRIPTION = "browkorf.settings.directional_navigation_mode.description"
    const val NEW_TAB_BUTTON_AT_START_DESCRIPTION = "browkorf.settings.new_tab_button_at_start.description"
    const val CONTEXT_MENU_ON_LONG_PRESS_DESCRIPTION = "browkorf.settings.context_menu_on_long_press.description"
    const val SINGLE_TAB_MODE_DESCRIPTION = "browkorf.settings.single_tab_mode.description"

    const val THEME_OPTIONS = "browkorf.settings.theme.options"
    const val HOME_PAGE_MODE_OPTIONS = "browkorf.settings.home_page_mode.options"
    const val SEARCH_ENGINE_OPTIONS = "browkorf.settings.search_engine.options"
    const val USER_AGENT_OPTIONS = "browkorf.settings.user_agent.options"
    const val WEB_ENGINE_OPTIONS = "browkorf.settings.web_engine.options"
    const val UPDATE_CHANNEL_OPTIONS = "browkorf.settings.update_channel.options"

    const val WEB_ENGINE_CONFIRMATION_TITLE = "browkorf.settings.web_engine.confirmation.title"
    const val WEB_ENGINE_CONFIRMATION_MESSAGE = "browkorf.settings.web_engine.confirmation.message"
}
