android.useAndroidX=true
android.experimental.kotlin.builtIn=true
android.experimental.android.extensions.update=true
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
android.enableR8.fullMode=true
#android.r8.failOnMissingClasses=false
android.r8.mapIdTemplate=0
#android.defaults.buildfeatures.resvalues=true
#android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
#android.usesSdkInManifest.disallowed=false
#android.uniquePackageNames=false
#android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
#android.builtInKotlin=false
#android.newDsl=false